#pragma once
#include <SDL2/SDL.h>
#include <glad/glad.h>
#include <imgui/imgui.h>
#include <imgui/imgui_impl_sdl2.h>
#include <imgui/imgui_impl_opengl3.h>
#include <spdlog/spdlog.h>
#include "Shader.h"
#include "Application.h"
#include "Debug.h"
#include "OGL/VBO.h"
#include "Texture.h"
#include "Transform.h"
#include "CameraBase.h"
#include "Primitives/Cube.h"
#include "Painter.h"
#include "Modules/PLYfile.h"
#include "Primitives/PointCloud.h"